version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root_user
      MONGO_INITDB_ROOT_PASSWORD: root_password
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

